#! /usr/bin/env bash

# open the page first to avoid complicated logic here so we need to refresh after a bit
xdg-open http://127.0.0.1:3000

npx github:lcwllmr/scimd watch web/index.md > /dev/null 2>&1
